import Head from 'next/head'
import Footer from '../components/Footer'
import { GlobalStyle } from '../styles/GlobalStyled'

function MyApp({ Component, pageProps }) {
  return (
    <>  
      <Head>
        <title>testes-next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png"/>
      </Head>
      <GlobalStyle />
      <Component {...pageProps} />
      <Footer />
    </>
  )
}

export default MyApp
