import Head from 'next/head'
import Image from 'next/image'
import styles from '../src/styles/Home.module.css'
import React from 'react';
import Modal from '../src/components/Modal/index'


export default function Home() {
  const [showModal, setShowModal] = React.useState(false);
  const [animateModal, setAnimateModal] = React.useState(false);


  const openModal = () => {
    setAnimateModal(true)
    setShowModal(true);
  }

  const closeModal = () => {
    setAnimateModal(false)
    setTimeout(()=> {
      setShowModal(false);
    }, 1000)
  }

  return (
    <div id="app" className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">next-modal</a>
        </h1>

        <p className={styles.description}>
          Get started by clicking this thing below
        </p>

        <div className={styles.grid}>
          <a
            className={styles.card}
            onClick={openModal}
          >
          <h2>Open &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>
        </div>

        {showModal && <Modal closeModal={closeModal} animateModal={animateModal} />}



      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
